version: '3.8'

services:
  data_gen:
    build: 
      context: ./services/data_gen
      dockerfile: Containerfile
    volumes:
      - ./data:/opt/data
    profiles: ["setup"]

  etl:
    build:
      context: ./services/etl
      dockerfile: Containerfile
    volumes:
      - ./data:/opt/data
